//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BFDataCrawler.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.8.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string _hobBWTeethShape {
            get {
                return ((string)(this["_hobBWTeethShape"]));
            }
            set {
                this["_hobBWTeethShape"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int _hobBWTeethQty {
            get {
                return ((int)(this["_hobBWTeethQty"]));
            }
            set {
                this["_hobBWTeethQty"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string _hobCNCTeethShape {
            get {
                return ((string)(this["_hobCNCTeethShape"]));
            }
            set {
                this["_hobCNCTeethShape"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int _hobCNCTeethQty {
            get {
                return ((int)(this["_hobCNCTeethQty"]));
            }
            set {
                this["_hobCNCTeethQty"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string _noHobBWTeethShape {
            get {
                return ((string)(this["_noHobBWTeethShape"]));
            }
            set {
                this["_noHobBWTeethShape"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int _noHobBWTeethQty {
            get {
                return ((int)(this["_noHobBWTeethQty"]));
            }
            set {
                this["_noHobBWTeethQty"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string _noHobCNCTeethShape {
            get {
                return ((string)(this["_noHobCNCTeethShape"]));
            }
            set {
                this["_noHobCNCTeethShape"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int _noHobCNCTeethQty {
            get {
                return ((int)(this["_noHobCNCTeethQty"]));
            }
            set {
                this["_noHobCNCTeethQty"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("PC_SPCF4@spclt.com.vn")]
        public string _spcMailSender {
            get {
                return ((string)(this["_spcMailSender"]));
            }
            set {
                this["_spcMailSender"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("PC_SPCF4@spclt.com.vn")]
        public string _spcMailReceiver {
            get {
                return ((string)(this["_spcMailReceiver"]));
            }
            set {
                this["_spcMailReceiver"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("spclt@123")]
        public string _spcMailCode {
            get {
                return ((string)(this["_spcMailCode"]));
            }
            set {
                this["_spcMailCode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string _hob11BW_TeethShape {
            get {
                return ((string)(this["_hob11BW_TeethShape"]));
            }
            set {
                this["_hob11BW_TeethShape"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string _hob12BW_TeethShape {
            get {
                return ((string)(this["_hob12BW_TeethShape"]));
            }
            set {
                this["_hob12BW_TeethShape"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string _hob9BWCNC_TeethShape {
            get {
                return ((string)(this["_hob9BWCNC_TeethShape"]));
            }
            set {
                this["_hob9BWCNC_TeethShape"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string _hob10BWCNC_TeethShape {
            get {
                return ((string)(this["_hob10BWCNC_TeethShape"]));
            }
            set {
                this["_hob10BWCNC_TeethShape"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string _hob9CNC_TeethShape {
            get {
                return ((string)(this["_hob9CNC_TeethShape"]));
            }
            set {
                this["_hob9CNC_TeethShape"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string _hob10CNC_TeethShape {
            get {
                return ((string)(this["_hob10CNC_TeethShape"]));
            }
            set {
                this["_hob10CNC_TeethShape"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int _hob11BW_TeethQuantity {
            get {
                return ((int)(this["_hob11BW_TeethQuantity"]));
            }
            set {
                this["_hob11BW_TeethQuantity"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int _hob12BW_TeethQuantity {
            get {
                return ((int)(this["_hob12BW_TeethQuantity"]));
            }
            set {
                this["_hob12BW_TeethQuantity"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int _hob9BWCNC_TeethQuantity {
            get {
                return ((int)(this["_hob9BWCNC_TeethQuantity"]));
            }
            set {
                this["_hob9BWCNC_TeethQuantity"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int _hob10BWCNC_TeethQuantity {
            get {
                return ((int)(this["_hob10BWCNC_TeethQuantity"]));
            }
            set {
                this["_hob10BWCNC_TeethQuantity"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int _hob9CNC_TeethQuantity {
            get {
                return ((int)(this["_hob9CNC_TeethQuantity"]));
            }
            set {
                this["_hob9CNC_TeethQuantity"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int _hob10CNC_TeethQuantity {
            get {
                return ((int)(this["_hob10CNC_TeethQuantity"]));
            }
            set {
                this["_hob10CNC_TeethQuantity"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double _hob11BW_Diameter {
            get {
                return ((double)(this["_hob11BW_Diameter"]));
            }
            set {
                this["_hob11BW_Diameter"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double _hob12BW_Diameter {
            get {
                return ((double)(this["_hob12BW_Diameter"]));
            }
            set {
                this["_hob12BW_Diameter"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double _hob9BWCNC_Diameter {
            get {
                return ((double)(this["_hob9BWCNC_Diameter"]));
            }
            set {
                this["_hob9BWCNC_Diameter"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double _hob10BWCNC_Diameter {
            get {
                return ((double)(this["_hob10BWCNC_Diameter"]));
            }
            set {
                this["_hob10BWCNC_Diameter"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double _noHobBW_Diameter {
            get {
                return ((double)(this["_noHobBW_Diameter"]));
            }
            set {
                this["_noHobBW_Diameter"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double _hob9CNC_Diameter {
            get {
                return ((double)(this["_hob9CNC_Diameter"]));
            }
            set {
                this["_hob9CNC_Diameter"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double _hob10CNC_Diameter {
            get {
                return ((double)(this["_hob10CNC_Diameter"]));
            }
            set {
                this["_hob10CNC_Diameter"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double _noHobCNC_Diameter {
            get {
                return ((double)(this["_noHobCNC_Diameter"]));
            }
            set {
                this["_noHobCNC_Diameter"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string _hob9BWCNC_DMat {
            get {
                return ((string)(this["_hob9BWCNC_DMat"]));
            }
            set {
                this["_hob9BWCNC_DMat"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string _hob10BWCNC_DMat {
            get {
                return ((string)(this["_hob10BWCNC_DMat"]));
            }
            set {
                this["_hob10BWCNC_DMat"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string _hob9CNC_DMat {
            get {
                return ((string)(this["_hob9CNC_DMat"]));
            }
            set {
                this["_hob9CNC_DMat"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string _hob10CNC_DMat {
            get {
                return ((string)(this["_hob10CNC_DMat"]));
            }
            set {
                this["_hob10CNC_DMat"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double _f1BW_Diameter {
            get {
                return ((double)(this["_f1BW_Diameter"]));
            }
            set {
                this["_f1BW_Diameter"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string _hob11BW_GlobalCode {
            get {
                return ((string)(this["_hob11BW_GlobalCode"]));
            }
            set {
                this["_hob11BW_GlobalCode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string _hob12BW_GlobalCode {
            get {
                return ((string)(this["_hob12BW_GlobalCode"]));
            }
            set {
                this["_hob12BW_GlobalCode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string _hob9BWCNC_GlobalCode {
            get {
                return ((string)(this["_hob9BWCNC_GlobalCode"]));
            }
            set {
                this["_hob9BWCNC_GlobalCode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string _hob10BWCNC_GlobalCode {
            get {
                return ((string)(this["_hob10BWCNC_GlobalCode"]));
            }
            set {
                this["_hob10BWCNC_GlobalCode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string _hob9CNC_GlobalCode {
            get {
                return ((string)(this["_hob9CNC_GlobalCode"]));
            }
            set {
                this["_hob9CNC_GlobalCode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string _hob10CNC_GlobalCode {
            get {
                return ((string)(this["_hob10CNC_GlobalCode"]));
            }
            set {
                this["_hob10CNC_GlobalCode"] = value;
            }
        }
    }
}
